[FileGenerationSettings]
# Generated files will use this extension
generatedFilesExtension = ".rfk.h"

# List of supported extensions
supportedExtensions		= [".h", ".hpp"]

# Generated files will be located here
outputDirectory			= '''Path/To/Output/Dir'''

# Files contained in the directories of this list will be parsed
toParseDirectories		= [
#	'''Path/To/Directory/To/Parse'''
]

# Files to parse which are not included in any directory of toParseDirectories
toParseFiles			= []

# Files contained in the directories of this list will be ignored
ignoredDirectories		= [
#	'''Path/To/Output/Dir''',
#	'''Path/To/Directory/To/Ignore'''
]

# Files not to parse which are not included in any directory of ignoredDirectories
ignoredFiles			= []


[FileParsingSettings]
# Abort parsing on first encountered error
shouldAbortParsingOnFirstError	= true

# Should all entities be parsed whether they are tagged with the macro or not
shouldParseAllEntities			= false

# Include directories of the project
projectIncludeDirectories		= [
#	'''Path/To/RefurekuLibrary/Include''',
#	'''Path/To/Your/Project/Include'''
]

[FileParsingSettings.Properties]
propertySeparator = ","
subPropertySeparator = ","
subPropertyStartEncloser = "("
subPropertyEndEncloser = ")"
ignoredCharacters = [ " " ]

namespaceMacroName = "RFKNamespace"
classmacroName = "RFKClass"
structMacroName = "RFKStruct"
fieldMacroName = "RFKField"
methodMacroName = "RFKMethod"
enumMacroName = "RFKEnum"
enumValueMacroName = "RFKEnumVal"