name: Build & Tests

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build Refureku

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configs: [Release, Debug]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2